name: CI
on:
  - workflow_dispatch

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: mxschmitt/action-tmate@v3
  macos:
    runs-on: macos-latest
    steps:
      - uses: mxschmitt/action-tmate@v3
  macos-15:
    runs-on: macos-15
    steps:
      - uses: mxschmitt/action-tmate@v3
